results: introduce the `no_clean` property
csutils/csmock pull request #109
Opened 2023-06-27 14:57 UTC by kdudka

If the `no_clean` property is set, the temporary directory is not automatically removed in the `__exit__` handler, which is useful for debugging.

2023-06-27 15:42 UTC, kdudka commented on py/common/results.py
> +    def __init__(self, output, tool, tool_version, keep_going=False, create_dbgdir=True, no_clean=False):
Fixed in commit dc2ac587682636e1fe40112c9684953f8afc4532.

2023-07-11 08:00 UTC, lzaoral requested changes

2023-07-11 08:00 UTC, lzaoral commented on py/common/results.py
> +
I'd merge this `if` statement body with the newly added `if` below because they have the same conditions.

2023-07-11 08:01 UTC, lzaoral approved these changes

2023-07-11 08:09 UTC, closed without merging