Code refactoring to enable reuse of the function handle_known_fp_list
csutils/csmock pull request #115
Opened 2023-08-16 01:49 UTC by lbossis

Ready for review

2023-08-16 07:27 UTC, kdudka reviewed
Thank you for working on this.  I am marking this pull request as a draft until the related change in `cspodman` is proven to work as expected.

2023-08-16 07:27 UTC, kdudka commented on py/common/util.py
>  import re
Please keep the imports alphabetically sorted.

2023-08-16 07:28 UTC, lzaoral commented on py/csmock
> +from csmock.common.util         import handle_known_fp_list
This needs to be sorted as well.

2023-08-22 07:44 UTC, kdudka commented
@lbossis Thank you for working on this. I am marking this pull request as a draft until the related change in cspodman is proven to work as expected.

2023-09-13 12:30 UTC, kdudka commented on py/common/util.py
> +    filter_cmd = f"csdiff --json-output --show-internal \"{props.known_false_positives}\""
@lbossis This would break `csmock` because `csdiff` takes two operands and you omitted the trailing `-`: https://github.com/csutils/csmock/blob/0671e2aaeaf9b1139aaee308b5dd79260e0e5df5/py/csmock#L676

2023-09-14 10:50 UTC, lzaoral requested changes
Test.

2023-09-21 09:08 UTC, rhyw commented
Didn't verify but the proposed changes LGTM.

2023-09-22 02:49 UTC, rhyw approved these changes

2023-09-22 10:29 UTC, kdudka commented
@rhyw Thanks for review!

2023-09-22 10:29 UTC, merged