plugins/semgrep: add csmock semgrep plugin
csutils/csmock pull request #149
Opened 2024-01-08 07:09 UTC by rhyw

Resolves: https://issues.redhat.com/browse/OSH-57

2024-01-08 08:16 UTC, kdudka requested changes

2024-01-08 08:16 UTC, kdudka commented on py/plugins/semgrep.py
> +            ec = results.exec_cmd(cmd, shell=True)
A csmock plug-in should not silently install anything in the host environment.  If it needs to download a tool from the Internet, it should use a separate cache directory that will not affect user's environment.

2024-01-08 08:16 UTC, kdudka commented on py/plugins/semgrep.py
> +            semgrep_bin_dir = os.path.abspath("./.local/bin")
Does the code expect `csmock` to be called in a specific directory?

2024-01-08 08:16 UTC, kdudka commented on py/plugins/semgrep.py
> +                results.error("Unexpected internal errors (bugs).")
These messages should ideally use the `semgrep: ` prefix to make it clear what failed from the error message itself.

2024-01-08 08:16 UTC, kdudka commented on py/plugins/semgrep.py
> +            cmd = FILTER_CMD % (src, dst)
Please use f-strings in newly introduced code.

2024-01-08 08:16 UTC, kdudka commented on py/plugins/semgrep.py
> +            props.copy_in_files += [SEMGREP_RULES_CACHE_DIR]
This will copy the rules into chroot but what about the semgrep tool itself?

2024-01-08 08:16 UTC, kdudka commented on py/plugins/semgrep.py
> +            ec = mock.exec_chroot_cmd(cmd)
This will run `semgrep` in the chroot environment after the tool was installed into the host environment.  How could this ever work?

2024-01-08 09:42 UTC, rhyw commented on py/plugins/semgrep.py
> +            cmd = FILTER_CMD % (src, dst)
Updated

2024-01-12 02:02 UTC, rhyw commented on py/plugins/semgrep.py
> +            ec = results.exec_cmd(cmd, shell=True)
Latest code updated to specify the install target.

2024-01-12 02:03 UTC, rhyw commented on py/plugins/semgrep.py
> +            semgrep_bin_dir = os.path.abspath("./.local/bin")
This was updated, by updating one-time `PATH`/`PYTHONPATH`.

2024-01-12 02:03 UTC, rhyw commented on py/plugins/semgrep.py
> +                results.error("Unexpected internal errors (bugs).")
Fixed

2024-01-12 02:03 UTC, rhyw commented on py/plugins/semgrep.py
> +            props.copy_in_files += [SEMGREP_RULES_CACHE_DIR]
rules should be located in host, this line was removed

2024-01-12 02:03 UTC, rhyw commented on py/plugins/semgrep.py
> +            ec = mock.exec_chroot_cmd(cmd)
Updated

2024-01-17 15:35 UTC, kdudka requested changes

2024-01-17 15:35 UTC, kdudka commented on py/plugins/semgrep.py
> +            cmd = f"python3 -m pip install --target={SEMGREP_LIB_TARGET_DIR} semgrep"
What will happen if we start 5 processes of `csmock -t semgrep ...` at the same time?  Will the shared cache directory always be in a consistent state after executing this command?

2024-01-17 15:35 UTC, kdudka commented on py/plugins/semgrep.py
> +                results.exec_cmd(["rm", "-rf", f"{SEMGREP_RULES_CACHE_DIR}/*"])
This will not work well if we run multiple `csmock -t semgrep ...` processes in parallel.

2024-01-17 15:35 UTC, kdudka commented on py/plugins/semgrep.py
> +SEMGREP_RULES_REPO = "https://git.prodsec.redhat.com/prodsec-services/masssast"
This URL is not publicly reachable and it is definitely not a good default for the upstream csmock project.

2024-01-17 15:35 UTC, kdudka commented on py/plugins/semgrep.py
> +SEMGREP_SEND_METRICS = "off"
The variables setting default values for options should start with the `DEFAULT_` prefix.

2024-01-17 15:35 UTC, kdudka commented on py/plugins/semgrep.py
> +                ec = results.exec_cmd(repo_clone_cmd.split())
Why do you use a format string to create a space-separated list to convert it to a list later on?  This would unnecessarily break e.g. if `SEMGREP_RULES_CACHE_DIR` contained a space.  It is much easier to read (and more robust at the same time) if you create the list directly:
```py
repo_clone_cmd = ["git", "clone", args.semgrep_rules_repo, SEMGREP_RULES_CACHE_DIR]
ec = results.exec_cmd(repo_clone_cmd)
```

2024-01-17 15:35 UTC, kdudka commented on py/plugins/semgrep.py
> +            cmd = f"mock -r {props.mock_profile} --print-root-path"
This needs to go through the `MockWrapper` abstraction.  Otherwise it would not work with `csmock --root-override ...` etc.:
```py
cmd = mock.get_mock_cmd(["--print-root-path"])
(ec, out) = results.get_cmd_output(cmd, shell=False)
```

2024-01-17 15:35 UTC, kdudka commented on py/plugins/semgrep.py
> +        def get_chroot_root_path(results, props):
Why is this a local function when it does not access anything local to `handle_args()`?

2024-01-17 16:29 UTC, kdudka commented on py/plugins/semgrep.py
> +            os.environ['PATH'] = f"{os.environ.get('PATH')}:{SEMGREP_LIB_TARGET_DIR}/bin"
As pointed out by @lzaoral, this will also prepend `None` to `${PYTHONPATH}` if the variable is initially unset.

2024-01-18 07:03 UTC, rhyw commented on make-srpm.sh
> +%files -n csmock-plugin-semgrep
updated

2024-01-18 07:52 UTC, rhyw commented on py/CMakeLists.txt
> +    install_plugin(semgrep)
updated

2024-01-18 07:52 UTC, rhyw commented on py/plugins/semgrep.py
> +SEMGREP_SEND_METRICS = "off"
updated

2024-01-18 07:52 UTC, rhyw commented on py/plugins/semgrep.py
> +        self.stable = True
updated

2024-01-18 07:52 UTC, rhyw commented on py/plugins/semgrep.py
> +SEMGREP_RULES_REPO = "https://git.prodsec.redhat.com/prodsec-services/masssast"
What do you suggest? by add a new repo in github under `csutils` and maintain those rules on our own?

2024-01-18 07:54 UTC, rhyw commented on py/plugins/semgrep.py
> +            cmd = f"python3 -m pip install --target={SEMGREP_LIB_TARGET_DIR} semgrep"
I don't think so. it's indeed unsafe if it's ran in parallel. I don't have a better idea how this could be done, unless the semgrep executable is installed before scan begins. i.e., `semgrep` as a install require while deploying the worker instead of installing at runtime. Is that an option?

2024-01-18 07:54 UTC, rhyw commented on py/plugins/semgrep.py
> +            os.environ['PATH'] = f"{os.environ.get('PATH')}:{SEMGREP_LIB_TARGET_DIR}/bin"
This only applies to current process. Other process won't be impacted.

2024-01-18 08:18 UTC, kdudka commented on py/plugins/semgrep.py
> +SEMGREP_RULES_REPO = "https://git.prodsec.redhat.com/prodsec-services/masssast"
If there is any well-maintained publicly available repository, we can use it as the default value.  If not, we should not provide any default URL and make this option mandatory so that the user provides it (assuming `semgrep` does not work without it).

2024-01-18 08:23 UTC, kdudka commented on py/plugins/semgrep.py
> +            os.environ['PATH'] = f"{os.environ.get('PATH')}:{SEMGREP_LIB_TARGET_DIR}/bin"
I do not understand what you are trying to say.  What do you mean by `current process`?  `csmock`,  `semgrep`, or something else?  It does not make any sense...

2024-01-18 08:27 UTC, kdudka commented on py/plugins/semgrep.py
> +            cmd = f"python3 -m pip install --target={SEMGREP_LIB_TARGET_DIR} semgrep"
Let's start with creating something that works reliably.  Optimizations can be introduced later as needed.  If we install `semgrep` into `results.tmpdir` without caching anything across `csmock` runs, it will be safe regarding parallel execution of `csmock`.

2024-01-19 03:55 UTC, rhyw commented on py/plugins/semgrep.py
> +            cmd = f"python3 -m pip install --target={SEMGREP_LIB_TARGET_DIR} semgrep"
sure. I'll update to make sure it's installed under `results.tmpdir`.

2024-01-19 03:55 UTC, rhyw commented on py/plugins/semgrep.py
> +            os.environ['PATH'] = f"{os.environ.get('PATH')}:{SEMGREP_LIB_TARGET_DIR}/bin"
The problem is that after the package is installed in a user-specified directory, the `bin`/`lib` directory is invisible, thus `PATH`/`PYTHONPATH` has to be amended to make it visible. 

> The environment should be changed only for commands invoked by this plug-in, rather than for all commands invoked by `csmock`.

I'm not sure I understand what this means. How am I supposed to make it visible without changing like this? Sorry for the confusion, I don't have a good understanding of how it works to be frank.

2024-01-19 03:55 UTC, rhyw commented on py/plugins/semgrep.py
> +SEMGREP_RULES_REPO = "https://git.prodsec.redhat.com/prodsec-services/masssast"
The offical semgrep-rules repo is well maintained, but it's unfortunate it cannot be used directly, i.e., I'll need to specify rules one by one, instead of by ruleset.

I tried several other open source rules repo, none seem to be qualified. I'll see if I could find one, otherwise I'll make it mandatory option. Didn't know that before till I see your comment.

2024-01-19 12:41 UTC, kdudka commented on py/plugins/semgrep.py
> +            os.environ['PATH'] = f"{os.environ.get('PATH')}:{SEMGREP_LIB_TARGET_DIR}/bin"
You only need to set variables when you invoke `semgrep`.

If you use shell (like in the `semgrep scan ...` command), you can just prepend the variables assignment to the command you want to execute:
```py
cmd = f"PYTHONPATH=\"{semgrep_lib_dir}:$PYTHONPATH\" {cmd}"
cmd = f"PATH=\"{semgrep_lib_dir}/bin:$PATH\" {cmd}"
```

If you use `exec` directly (like in the `["semgrep", "--version"]` command), you can wrap the command by `env(1)` to set the environment:
```py
cmd = ["semgrep", "--version"]
cmd = ["env", f"PATH={path_for_semgrep}", f"PYTHONPATH={pythonpath_for_semgrep}"] + cmd
```

I would suggest to use one approach for both the commands so that the code for env handling can be shared.

2024-01-22 02:56 UTC, rhyw commented on py/plugins/semgrep.py
> +            os.environ['PATH'] = f"{os.environ.get('PATH')}:{SEMGREP_LIB_TARGET_DIR}/bin"
Thanks. I'll update this way!

2024-01-24 06:27 UTC, rhyw commented on py/plugins/semgrep.py
> +        def get_chroot_root_path(results, props):
I use it as a shortcut to get chroot root path. anyway it's not really necessary. Removed.

2024-01-24 06:28 UTC, rhyw commented on py/plugins/semgrep.py
> +            cmd = f"mock -r {props.mock_profile} --print-root-path"
updated

2024-01-26 14:46 UTC, kdudka requested changes
We need to update csdiff to recognize the `semgrep` tool and report the findings as `SEMGREP_WARNING` rather than `UNKNOWN_SARIF_WARNING`.

Please also remove the trailing dot from the git commit title: `... in make-srpm.sh.`

2024-01-26 14:46 UTC, kdudka commented on py/plugins/semgrep.py
> +            "--semgrep-rules-repo", required=True,
You cannot require the option this way because it would fail all scans where `semgrep` is not enabled (as long as this csmock plug-in is installed).

2024-01-26 14:46 UTC, kdudka commented on py/plugins/semgrep.py
> +            repo_clone_cmd = ["git", "clone", args.semgrep_rules_repo, semgrep_rules_repo_dir]
Unless you want to checkout a specific snapshot of the repo, you should clone with `--depth=1` to avoid fetching git objects that will not be used.

2024-01-26 14:46 UTC, kdudka commented on py/plugins/semgrep.py
> +        # set to True to include this plug-in in `csmock --all-tools`
Please update the comment.  It does not make sense to enable the plug-in with `--all-tools` when it requires some extra options.  Plug-ins enabled by `--all-tools` need to work out of the box.

2024-01-26 14:46 UTC, kdudka commented on py/plugins/semgrep.py
> +                os.makedirs(semgrep_rules_repo_dir, mode=0o755, exist_ok=True)
You do not need to create the directory in advance.  `git-clone` will create it if it does not exist.

2024-01-26 14:46 UTC, kdudka commented on py/plugins/semgrep.py
> +            cmd = f"csgrep '{src}' --mode=json --prepend-path-prefix={SEMGREP_SCAN_DIR}/ > '{dst}'"
This looks wrong.  Did you intend to use `--strip-path-prefix` instead?

2024-01-30 07:51 UTC, rhyw commented on py/plugins/semgrep.py
> +            cmd = f"csgrep '{src}' --mode=json --prepend-path-prefix={SEMGREP_SCAN_DIR}/ > '{dst}'"
I guess so. I know little about the csdiff options. After updated and I got below records in the output json:
```
    "defects": [
        {
            "checker": "UNKNOWN_SARIF_WARNING",
            "tool": "unknown-sarif",
            "key_event_idx": 0,
            "events": [
                {
                    "file_name": "/var/lib/mock/rhel-8.5.0.z-x86_64/root/builddir/build/BUILD/gzip-1.9/tests/list",
                    "line": 28,
                    "column": 1,
                    "event": "warning[tmp.csmocksyi3zdu7.semgrep_rules.rules.semgrep-rules.bash.lang.best-practice.useless-cat]",
                    "message": "Useless call to 'cat' in a pipeline. Use '<' and '>' for any command to read from a file or write to a file.",
                    "verbosity_level": 0
                }
            ]
        },
...
]
```

Is the path in it correct?

2024-01-30 07:52 UTC, rhyw commented on py/plugins/semgrep.py
> +                os.makedirs(semgrep_rules_repo_dir, mode=0o755, exist_ok=True)
Removed in latest patch.

2024-01-30 07:52 UTC, rhyw commented on py/plugins/semgrep.py
> +        # set to True to include this plug-in in `csmock --all-tools`
I removed this comment.

2024-01-30 07:52 UTC, rhyw commented on py/plugins/semgrep.py
> +            repo_clone_cmd = ["git", "clone", args.semgrep_rules_repo, semgrep_rules_repo_dir]
added.

2024-01-30 07:53 UTC, rhyw commented on py/plugins/semgrep.py
> +            "--semgrep-rules-repo", required=True,
I get it. So I've updated in `handle_args` by a `parser.error` instead. Please review.

2024-01-30 08:03 UTC, rhyw commented
I think i've addressed all the issues within this patch. The remaining issue is to update csdiff to recognize "SEMGREP_WARNING" instead of "UNKNOWN_SARIF_WARNING".

I'm not sure if I can do that since it's written in C++ .  I could give it a try later this week.

2024-01-30 08:38 UTC, kdudka commented on py/plugins/semgrep.py
> +            cmd = f"csgrep '{src}' --mode=json --prepend-path-prefix={SEMGREP_SCAN_DIR}/ > '{dst}'"
Obviously not.  The path should be `gzip-1.9/tests/list`.  The paths in the scan results need to be specific to the project being scanned, not to the scanning environment.  Such prefixes would break deduplication of findings and elimination of false positives.  You can run `csmock --all-tools` on the same package to see how the file paths look like with the already integrated scanners.

2024-01-30 08:51 UTC, kdudka commented
> I think i've addressed all the issues within this patch. The remaining issue is to update csdiff to recognize "SEMGREP_WARNING" instead of "UNKNOWN_SARIF_WARNING".

You can see how this was done for the Gitleaks tool: https://github.com/csutils/csdiff/commit/54e87362c45d2d774b948bf07298c79ba91a2d54

> I'm not sure if I can do that since it's written in C++ . I could give it a try later this week.

Please ask @hanchuntao for help.  He was already reviewing some csdiff pull requests.

2024-01-30 08:53 UTC, lzaoral commented on py/plugins/semgrep.py
> +            cmd = f"csgrep '{src}' --mode=json --prepend-path-prefix={SEMGREP_SCAN_DIR}/ > '{dst}'"
The `event` key also looks a bit suspicious:
```json
"event": "warning[tmp.csmocksyi3zdu7.semgrep_rules.rules.semgrep-rules.bash.lang.best-practice.useless-cat]",
                  ^^^^^^^^^^^^^^^^^^^
```

2024-02-05 12:01 UTC, rhyw commented on py/plugins/semgrep.py
> +            cmd = f"csgrep '{src}' --mode=json --prepend-path-prefix={SEMGREP_SCAN_DIR}/ > '{dst}'"
I'm now working on the csdiff c++ patch to recognize semgrep warnings.

2024-02-06 14:13 UTC, jperezdealgaba commented
@rhyw Do we have a reproducer for this? And second, are PyLint findings going to be addressed?

2024-02-06 15:47 UTC, rhyw commented
> @rhyw Do we have a reproducer for this? And second, are PyLint findings going to be addressed?

I tested by `csmock -r /etc/mock/rhel-8.5.0.z-x86_64.cfg -t semgrep --semgrep-rules-repo=<the-internal-masssast-repo> --force gzip-1.9-13.el8_5.src.rpm`. However we'll need a renewed `csgrep` package(build from https://github.com/csutils/csdiff/pull/162) to verify the warning recognition.

As for Pylint warning, yeah they're very anonying. I'm curious how other modules survived this. I'll give an update tomorrow, to resolve as much as I can.

2024-02-07 03:03 UTC, rhyw commented on py/plugins/semgrep.py
> +            cmd = f"csgrep '{src}' --mode=json --prepend-path-prefix={SEMGREP_SCAN_DIR}/ > '{dst}'"
MR: https://github.com/csutils/csdiff/pull/162

2024-02-13 11:46 UTC, kdudka commented on py/plugins/semgrep.py
> +            cmd = f"csgrep '{src}' --mode=json --prepend-path-prefix={SEMGREP_SCAN_DIR}/ > '{dst}'"
The csdiff merge request is unrelated to the path striping.  The problem mentioned by @lzaoral has not been fixed.   The event name `warning[csmockexonlktd.semgrep_rules.rules.semgrep-rules.bash.lang.correctness.unquoted-variable-expansion-in-command]` should obviously not contain name of the temporary directory, which is different for each run.

2024-02-19 01:54 UTC, rhyw commented on py/plugins/semgrep.py
> +            cmd = f"csgrep '{src}' --mode=json --prepend-path-prefix={SEMGREP_SCAN_DIR}/ > '{dst}'"
the csdiff MR was for warning recgonition. the temp rules path was stripped in this MR. see https://github.com/csutils/csmock/pull/149/files#diff-4efa9af9c12deec9697e4bff1d259e971df87c11cbc0a5e99eaee5633f914e78R210

2024-02-19 08:07 UTC, kdudka commented on py/plugins/semgrep.py
> +            cmd = f"csgrep '{src}' --mode=json --prepend-path-prefix={SEMGREP_SCAN_DIR}/ > '{dst}'"
I am still getting `warning[csmockc_n6ld1p.semgrep_rules.rules.semgrep-rules.bash.lang.correctness.unquoted-variable-expansion-in-command]` with the latest version of your pull request.  You also need to rebase your changes on top of `main`.

2024-02-21 11:32 UTC, rhyw commented on py/plugins/semgrep.py
> +            cmd = f"csgrep '{src}' --mode=json --prepend-path-prefix={SEMGREP_SCAN_DIR}/ > '{dst}'"
The root cause is that if the semgrep scan was run under `/tmp`, which happens to be the same directory with where the rules were located, the semgrep would strip the preceding `/tmp.` automatically in this case. The sed command takes effect when it's run elsewhere other than `tmp.`. 

I've updated the sed with `sed 's|[^[:space:]\"]*{tmp_path}||`, so that it strips the path no matter whether "tmp" is in or not. Please review!

2024-02-26 15:20 UTC, kdudka commented on py/plugins/semgrep.py
> +            cmd = f"csgrep '{src}' --mode=json --prepend-path-prefix={SEMGREP_SCAN_DIR}/ > '{dst}'"
As discussed on Slack, the `sed` command does not seem to work as expected.  Please look at `debug/scan-results-all.js` - the values assigned to the `event` fields are obviously invalid.  They contain non-matching `]`.

2024-02-27 10:06 UTC, rhyw commented on py/plugins/semgrep.py
> +            cmd = f"csgrep '{src}' --mode=json --prepend-path-prefix={SEMGREP_SCAN_DIR}/ > '{dst}'"
It appears the previous sed has unintendedly stripped the left square bracket. I've simplified the sed by using `sed 's|[^\[]*{tmp_path}||'` since I noticed that the non-whitespace/non-double-quote is not needed, and should be using non-square bracket instead.

I had several tests and it's working as expected. Please take a look. Apologies for the inconveniences it brings.

2024-02-27 13:18 UTC, kdudka requested changes

2024-02-28 00:21 UTC, rhyw commented on py/plugins/semgrep.py
> +            help="configures how usage metrics are sent to the Semgrep server",
This was actually the helper message from `--metrics` doc. Anyway updated.

2024-02-28 00:22 UTC, rhyw commented on py/plugins/semgrep.py
> +            help="show more details about what rules are running, which files failed to parse, etc",
providing default value is indeed confusing. I've updated to use `store_true` instead, and removed the redundant default.

2024-02-28 00:22 UTC, rhyw commented on py/plugins/semgrep.py
> +                "1",
updated

2024-02-28 00:22 UTC, rhyw commented on py/plugins/semgrep.py
> +            # any sequence of non left-square-bracket charactors preceding '{tmp_path}'
updated.

2024-02-28 00:22 UTC, rhyw commented on py/plugins/semgrep.py
> +# Copyright (C) 2014 Red Hat, Inc.
updated.

2024-02-28 12:57 UTC, kdudka commented on py/plugins/semgrep.py
> +            help="configures how usage metrics are sent to the Semgrep server",
I have further tweaked this in d1c58c4812556f653e7edad67d712fafe5b7d6fd.

2024-02-28 13:07 UTC, kdudka commented on py/plugins/semgrep.py
> +SEMGREP_CLI_VERSION = "1.56.0"
Do we want to use version 1.56.0 specifically?  The current latest release is 1.63.0.  At minimum, we should put here a comment explaining where to check for a more recent version of Semgrep, as proposed in a2ecae5360a52bb0aec94cacb64957f8f7e4198d.

2024-02-29 02:37 UTC, rhyw commented on py/plugins/semgrep.py
> +SEMGREP_CLI_VERSION = "1.56.0"
the rules used is incompatible with a newer cli: https://gitlab.cee.redhat.com/prodsec-services/masast/-/issues/1

I think tests are needed against the rules for newer cli release unless rules are generic enough.

2024-03-04 08:11 UTC, rhyw commented
Any more updates needed please?

2024-03-06 16:52 UTC, kdudka commented on py/plugins/semgrep.py
> +        def fetch_semgrep_rules_hook(results, props):
The comment and name of the function are misleading because the function not only downloads the rules but mainly installs the semgrep tool itself.

2024-03-06 16:52 UTC, kdudka commented on py/plugins/semgrep.py
> +            ec, output = results.get_cmd_output(mock.get_mock_cmd(["--print-root-path"]), shell=False)
This step should not be needed any more.  You can get the information from `mock.mock_root`, thanks to #151.

2024-03-07 06:13 UTC, rhyw commented on py/plugins/semgrep.py
> +        def fetch_semgrep_rules_hook(results, props):
that's indeed confusing. addressed in 2f274c484674de415abbdcb6de7bc9175ddff178

2024-03-07 06:15 UTC, rhyw commented on py/plugins/semgrep.py
> +            ec, output = results.get_cmd_output(mock.get_mock_cmd(["--print-root-path"]), shell=False)
Thanks, addressed in a79095cc48c897d858e753164100c3034a1c904a

2024-03-18 08:55 UTC, kdudka commented
@rhyw Did you look at the warnings produced by Differential PyLint?  For example, this one looks valid:
```
Error: PYLINT_WARNING:
py/plugins/semgrep.py:83:4: R1710[inconsistent-return-statements]: Plugin.handle_args: Either all return statements in a function should return an expression, or none of them should.
```

As far as I can see, no other csmock plug-in returns any value from `handle_args()`.  I find it confusing that the `semgrep` plug-in (in some cases) does.

2024-03-20 16:46 UTC, kdudka requested changes

2024-03-20 16:46 UTC, kdudka commented on py/plugins/semgrep.py
> +                semgrep_scan_cmd += f" {args.semgrep_scan_opts}"
This introduces a shell injection vulnerability as described at [CVE-2024-2243](https://bugzilla.redhat.com/CVE-2024-2243) but with higher impact because this command does not run in the isolated `mock` environment.  Please use `sanitize_opts_arg()` from `csmock.common.util` to sanitize the input.

2024-03-21 03:40 UTC, rhyw commented on py/plugins/semgrep.py
> +                semgrep_scan_cmd += f" {args.semgrep_scan_opts}"
addressed in 8c4dbfb10169487c59809730fe71415a393794d8

@kdudka However I think `sanitize_opts_arg()` needs update to work with non-snyk opts, specifically https://github.com/rhyw/csmock/blob/main/py/common/util.py#L53

2024-03-21 06:22 UTC, rhyw commented on py/plugins/semgrep.py
> +                semgrep_scan_cmd += f" {args.semgrep_scan_opts}"
Fix attempt: https://github.com/csutils/csmock/pull/156

2024-03-21 07:03 UTC, kdudka commented on py/plugins/semgrep.py
> +                semgrep_scan_cmd += f" {args.semgrep_scan_opts}"
Sorry for the copy/paste error.  The commit in in question did not go through the usual upstream review process because of the embargo and it somehow slipped through the internal review.

2024-03-21 12:27 UTC, lzaoral commented
@rhyw It is possible to execute the semgrep plugin without any need for additional resources?  If yes, could you please a test description for it?  You can take a look at the one for the GCC plugin as the inspiration: https://github.com/csutils/csmock/commit/219e34ee4daeb0be0028f50ce194e917b1de4dce

2024-03-21 13:10 UTC, kdudka commented
@lzaoral If we want to extend test coverage, I would focus on plug-ins with `self.stable = True` in `PluginProps`.  All other plug-ins are experimental.  This plug-in downloads the full software stack of `semgrep` over network, which is going to be slow and prone to fail for gazillion of reasons unrelated to the changes of `csmock` code.

2024-03-21 13:38 UTC, kdudka requested changes

2024-03-21 13:38 UTC, kdudka commented on py/plugins/semgrep.py
> +                results.error("semgrep: Unexpected internal errors (bugs).")
The error handling is wrong.  There needs to be a catch-all `else` branch to handle any error code that is not special-cased above.  I tried to run `csmock` like this:
```
csmock -r fedora-40-x86_64 -t semgrep -f /home/kdudka/git/csmock/csmock-3.5.3.20240321.201842.g4014c4e.pr_149-1.fc39.src.rpm --semgrep-scan-opts='--help; cat /home/kdudka/.config/configstore/snyk.json #' --semgrep-rules-repo=https://gitlab.cee.redhat.com/prodsec-services/masssast.git
```
... and it finished successfully despite `semgrep-scan.log` contained:
```
semgrep scan: unknown option '--help;', did you mean '--help'?
Usage: semgrep scan [OPTION]… [TARGETS]…
Try 'semgrep scan --help' for more information.
Error: fatal error
Exiting with error status 2: osemgrep scan --metrics=off --sarif --config=/tmp/csmockngt2zd0y/semgrep_rules/rules --help; cat /home/kdudka/.config/configstore/snyk.json # --output=/var/lib/mock/fedora-40-x86_64/root//builddir/semgrep-scan-results.sarif /var/lib/mock/fedora-40-x86_64/root//builddir/build/BUILD
```

2024-03-26 09:43 UTC, rhyw commented on py/plugins/semgrep.py
> +    def get_props(self):  # pylint: disable=missing-function-docstring
without this, pylint raises a warning.

2024-03-26 09:48 UTC, rhyw commented on py/plugins/semgrep.py
> +        self.semgrep_scan_opts = sanitize_opts_arg(parser, args, "--semgrep-scan-opts")
This is to be consistent with other plugins setup. moving it to `__init__` requires updates in the callee(py/csmock::main), which may require updates of other plugins too.

2024-03-26 09:49 UTC, rhyw commented on py/plugins/semgrep.py
> +                results.error("failed to install semgrep cli using pip")
good catch, I'll update to return values consistently.

2024-03-26 10:10 UTC, rhyw commented on py/plugins/semgrep.py
> +            version = output.rstrip("\n")
both should work, but I think `rstrip` is better because there is no leading `\n` in the output.

2024-03-26 10:13 UTC, rhyw commented on py/plugins/semgrep.py
> +            semgrep_lib_dir = os.path.join(results.tmpdir, "semgrep_lib")
Although this should also work, the top level `semgrep` needs to exist. The rules repo is specified by user and a repo clone would create the rules directory automatically, putting the rules inside the `semgrep` adds a pre-requisite.

2024-03-26 10:13 UTC, rhyw commented on py/plugins/semgrep.py
> +            version = output.rstrip("\n")
both should work, but I think `rstrip` is better because there is no leading `\n` in the output.

2024-03-27 09:29 UTC, rhyw commented on py/plugins/semgrep.py
> +        self.semgrep_scan_opts = sanitize_opts_arg(parser, args, "--semgrep-scan-opts")
I mis-interpreted this. Thanks, addressed in 1d0a24ff1dd6f4a007c95291fe83ecd9ee36ca30

2024-03-27 09:29 UTC, rhyw commented on py/plugins/semgrep.py
> +                results.error("failed to install semgrep cli using pip")
addressed in 66f0ce1a0dba5fa73725199c49af13ed306cba0e

2024-03-27 09:34 UTC, rhyw commented on py/plugins/semgrep.py
> +                results.error("semgrep: Unexpected internal errors (bugs).")
addressed in 66f0ce1a0dba5fa73725199c49af13ed306cba0e 

had some tests, if unrecognized opts were specified, it should raise error as below:
```
!!! 2024-03-27 04:54:01 error: semgrep: Scan failed with exit code 2. Command: env PATH=/tmp/csmocktczvra25/semgrep_lib/bin:$PATH PYTHONPATH=/tmp/csmocktczvra25/semgrep_lib semgrep scan --metrics=off --sarif --config=/tmp/csmocktczvra25/semgrep_rules/rules '--help;' cat /home/kdudka/.config/configstore/snyk.json '#' --output=/var/lib/mock/rhel-9-x86_64/root//builddir/semgrep-scan-results.sarif /var/lib/mock/rhel-9-x86_64/root//builddir/build/BUILD 2>/var/lib/mock/rhel-9-x86_64/root//builddir/semgrep-scan.log

>>> 2024-03-27 04:54:01 "'/usr/bin/mock' '-r' '/etc/mock/rhel-9-x86_64.cfg' '--plugin-option=tmpfs:keep_mounted=True' '--config-opts=print_main_output=True' '--quiet' '--shell' 'tar -c --remove-files '/builddir/semgrep-scan-results.sarif' '/builddir/semgrep-scan.log' '/builddir/semgrep-chroot-root'' | tar -xC '/tmp/csmocktczvra25/gzip-1.10-9.el9_0/debug/raw-results'"
tar: Removing leading `/' from member names
tar: /builddir/semgrep-scan-results.sarif: Cannot stat: No such file or directory
tar: Removing leading `/' from hard link targets
tar: Exiting with failure status due to previous errors

>>> 2024-03-27 04:54:02 "/usr/bin/mock" "-r" "/etc/mock/rhel-9-x86_64.cfg" "--plugin-option=tmpfs:keep_mounted=True" "--config-opts=print_main_output=True" "--quiet" "--clean"

scan.ini: time-finished = 2024-03-27 04:54:04
scan.ini: exit-code = 1
<<< 2024-03-27 04:54:04 csmock exit code: 1
```

2024-03-27 11:54 UTC, kdudka commented
@rhyw Looks good.  Please squash the fixup commits.  Namely 4014c4e1b1d52993974feb9f39dfcb418cde5811 needs to be squashed before merging so that we do not unnecessarily introduce and fix a security issue in the git history.

2024-03-28 08:03 UTC, rhyw commented
> @rhyw Looks good. Please squash the fixup commits. Namely [4014c4e](https://github.com/csutils/csmock/commit/4014c4e1b1d52993974feb9f39dfcb418cde5811) needs to be squashed before merging so that we do not unnecessarily introduce and fix a security issue in the git history.

Thanks, commits squashed

2024-03-28 13:40 UTC, kdudka commented
@rhyw Thanks!  I have squashed my fixup commits, too.  We do not want them in the `main` branch.

2024-03-28 13:41 UTC, kdudka approved these changes

2024-04-02 01:47 UTC, merged