csmock: use the root mock profile property for lock names
csutils/csmock pull request #151
Opened 2024-02-19 16:25 UTC by lzaoral

To fix a crash when two mock profile configuration files have different names but use the same root directory:
```
[...]
>>> 2024-02-19 14:29:12	"/usr/bin/mock" "-r" "/tmp/tmpyfvruenl/mock.cfg" "--plugin-option=tmpfs:keep_mounted=True" "--config-opts=print_main_output=True" "--init"
INFO: mock.py version 5.2 starting (python version = 3.9.18, NVR = mock-5.2-1.kdudka.5.el9), args: /usr/libexec/mock/mock -r /tmp/tmpyfvruenl/mock.cfg --plugin-option=tmpfs:keep_mounted=True --config-opts=print_main_output=True --init
Start(bootstrap): init plugins
INFO: selinux enabled
Finish(bootstrap): init plugins
Start: init plugins
INFO: selinux enabled
Finish: init plugins
INFO: Signal handler active
Start: run
Start: clean chroot
ERROR: Build root is locked by another process.

!!! 2024-02-19 14:29:13	warning: failed to init mock profile (/tmp/tmpyfvruenl/mock.cfg), trying to scrub cache...
[...]
```

Resolves: https://github.com/openscanhub/openscanhub/pull/228#discussion_r1494645666

2024-02-20 08:13 UTC, kdudka requested changes
Would it make sense to cache the `root_path` value in the `MockWrapper` object so that it can be used at other places (e.g. in the `semgrep` plug-in) without querying it again?

2024-02-20 08:13 UTC, kdudka commented on py/csmock
> +        ec, buildroot_dir = results.get_cmd_output(['mock', '-r', self.mock_profile, '--print-root-path'],
You should remove the trailing newline from the output.  Otherwise it looks like this:
```
[...]
>>> 2024-02-20 09:06:04 "rpm -qa | sort -V > '/tmp/csmockdjcpcck3/csmock-3.5.1-1.fc41/debug/rpm-list-host.txt'"

>>> 2024-02-20 09:06:06 tip: you can use --root-override=<directory> to run this csmock instance in parallel
>>> 2024-02-20 09:06:06 waiting till /tmp/.csmock-_var_lib_mock_rhel-9-x86_64_root_
.lock (PID 2508) disappears...
>>> 2024-02-20 09:07:06 waiting till /tmp/.csmock-_var_lib_mock_rhel-9-x86_64_root_
.lock (PID 2508) disappears...
```

2024-02-20 08:13 UTC, kdudka commented on py/csmock
> +        lock = f"/tmp/.csmock-" + (self.mock_root_override or buildroot_dir).replace('/','_')
You only use `buildroot_dir` if `mock_root_override` is None.  If `mock_root_override` is set, it does not make much sense to execute `--print-root-path` first.

2024-02-20 09:11 UTC, lzaoral commented on py/csmock
> +        lock = f"/tmp/.csmock-" + (self.mock_root_override or buildroot_dir).replace('/','_')
You are right, but due to https://github.com/csutils/csmock/pull/151#pullrequestreview-1889723365 it is going to be executed always.

2024-02-20 09:24 UTC, lzaoral commented
All suggestions addressed in or obsoleted by [87dfa62](https://github.com/csutils/csmock/pull/151/commits/87dfa62612854f946ba56080adb7007ef5bf7014).

2024-02-20 17:02 UTC, kdudka commented on py/csmock
> +        lock = f"/tmp/.csmock-" + (self.mock_root_override or buildroot_dir).replace('/','_')
@lzaoral Why?  If `props.mock_root_override` is set when `MockWrapper` is constructed, we should cache its value.  The value specified in mock config does not really matter if we are going to override it in each `mock` command executed through the `MockWrapper` object.

2024-02-20 17:05 UTC, kdudka commented on py/csmock
> +        ec, self.mock_root = results.get_cmd_output(['mock', '-r', self.mock_profile, '--print-root-path'],
I find this difficult to read.  Could we perhaps format it like this?
```py
cmd = ['mock', '-r', self.mock_profile, '--print-root-path']
ec, self.mock_root = results.get_cmd_output(cmd, shell=False)
```

2024-02-21 09:16 UTC, lzaoral commented on py/csmock
> +        lock = f"/tmp/.csmock-" + (self.mock_root_override or buildroot_dir).replace('/','_')
Got it!  Addressed in 9b24649def5973cc02bda1404cd3233f5de9f246.

2024-02-21 09:17 UTC, lzaoral commented on py/csmock
> +        ec, self.mock_root = results.get_cmd_output(['mock', '-r', self.mock_profile, '--print-root-path'],
Addressed in 9b24649def5973cc02bda1404cd3233f5de9f246.

2024-02-26 15:48 UTC, kdudka commented on py/csmock
> +        lock = f"/tmp/.csmock-" + self.mock_root.replace('/','_').strip()
This makes it incompatible with how `csmock` works today.  To stay compatible, we should take only the base name of the `root` directory.  Otherwise `csmock` will start to use a new lock name after update and could clash with the already running instances.

2024-02-26 16:15 UTC, lzaoral commented on py/csmock
> +        lock = f"/tmp/.csmock-" + self.mock_root.replace('/','_').strip()
Addressed in 5a0d5c1ae10cad0fa53e7bb85d6c93b8e187c766.

2024-02-26 16:50 UTC, kdudka commented on py/csmock
> +        lock_name = (self.mock_root_override or os.path.basename(self.mock_root)).replace('/','_')
Sorry, my suggestion to use `basename()` was totally off.

`os.path.basename("/var/lib/mock/rhel-9-x86_64/root/")` returns an empty string whereas we need to get `rhel-9-x86_64` out of it (without the `/root/` suffix).

2024-02-27 14:43 UTC, merged