snyk: added snyk stats to metadata
csutils/csmock pull request #153
Opened 2024-02-20 10:39 UTC by jperezdealgaba

Related: https://issues.redhat.com/browse/OSH-347
Reproducer: csmock -t snyk --force -r rhel-8-x86_64 osbuild-106-1.el10+4.src.rpm

Added the stats from snyk results (snyk coverage rate, analyzed files and total of files) to the metadata file.

2024-02-20 10:42 UTC, jperezdealgaba commented on py/plugins/snyk.py
> +            return snyk_write_analysis_meta(results, results_file)
Note: In the future, the `results_file` variable should be always the same path, but until the chroot/snyk problem is not solved, we need to have two different paths.

2024-02-26 14:57 UTC, kdudka requested changes
The newly introduced module needs to be installed by CMake to keep the RPM packaging (or local installations) working: https://github.com/csutils/csmock/blob/9befcc342fdf58f28accadd9fd5a7526059a423f/py/CMakeLists.txt#L23

2024-02-26 14:59 UTC, kdudka commented
> The newly introduced module needs to be installed by CMake...

@jperezdealgaba Note that this problem had already been revealed by the failing CI tests.

2024-02-26 16:13 UTC, lzaoral requested changes

2024-02-26 16:31 UTC, jperezdealgaba commented on py/plugins/snyk.py
> +from csmock.common.snyk import snyk_write_analysis_meta
@kdudka I have added the file to the CMake file. 
I have built the rpms locally and the new files are included in the src.rpms. Is something else needed?

2024-02-27 11:24 UTC, kdudka requested changes

2024-02-27 11:24 UTC, kdudka commented on py/common/snyk.py
> +# standard imports
Please include the license header as we do in other files in `py/common`.

2024-02-27 11:24 UTC, kdudka commented on py/common/snyk.py
> +    """write snyk stats on metatadata file. At the time, we write the total number of files,
`metatadata` -> `metadata`

2024-02-27 11:24 UTC, kdudka commented on py/common/snyk.py
> +        results.error(f"snyk-scan: snyk-results.sarif file not found: {e}")
`OSError` can be returned also in other cases, such as insufficient permissions to access the file, so the error message should be more generic, e.g.: `... failed to read {raw_results_file}: {e}`

2024-02-27 16:52 UTC, jperezdealgaba commented on py/common/snyk.py
> +# Copyright (C) 2024 Red Hat, Inc.
@kdudka I have updated the license header to refer to 2024. Should I do another commit to update plugin/snyk header?

2024-02-28 07:24 UTC, kdudka commented on py/common/snyk.py
> +# Copyright (C) 2024 Red Hat, Inc.
@jperezdealgaba Thanks!  I do not think it is critical.  We may eventually migrate `csutils` to use the two-lines SPDX license headers like we did for OSH: https://github.com/openscanhub/openscanhub/commit/31156512208145d032c470018cb338bb219e2059

@lzaoral What do you think about it?

2024-02-28 08:56 UTC, lzaoral commented on py/common/snyk.py
> +# Copyright (C) 2024 Red Hat, Inc.
@kdudka It is not necessary.

2024-02-28 11:27 UTC, kdudka commented on py/common/snyk.py
> +# Copyright (C) 2024 Red Hat, Inc.
@lzaoral Sure.  I was just thinking about modernization of `csutils` so that we do not waste time on maintaining the legacy GPL headers in source code files.

2024-02-28 11:37 UTC, lzaoral commented on py/common/snyk.py
> +# Copyright (C) 2024 Red Hat, Inc.
@kdudka I was reacting to @jperezdealgaba's idea.

Of course, I agree with modernisation of licensing information.

2024-02-28 12:44 UTC, kdudka approved these changes
Looks good.  Thanks for the update!

2024-02-28 12:46 UTC, merged