csmock: add `--scrub` option
csutils/csmock pull request #154
Opened 2024-02-20 13:55 UTC by lzaoral

... to pass `--scrub=all` to the underlying `mock` instance.

Related: https://github.com/openscanhub/openscanhub/pull/228#discussion_r1494707783

2024-02-20 13:59 UTC, lzaoral commented
@praiskup It seems that differential PyLint reports a problem in a piece of code that was edited in this PR. 🤔

2024-02-20 17:11 UTC, kdudka requested changes
Should we handle it better when someone uses both `--scrub` and `--no-clean`?

2024-02-20 17:11 UTC, kdudka commented on py/csmock
> +        "--scrub", action="store_true",
I would make the option name more specific, such as `--scrub-on-exit` or `--scrub-after-scan`.

2024-02-21 12:00 UTC, lzaoral commented on py/csmock
> +        "--scrub", action="store_true",
Addressed in 3b0f6953f2c429d93d8d98f3d44eddfdcd5a9644.

2024-02-26 16:03 UTC, merged