rust-clippy: fixes
csutils/csmock pull request #164
Opened 2024-05-03 12:13 UTC by petr-matousek

this is a follow up to https://github.com/csutils/csmock/pull/157

2024-05-03 12:14 UTC, petr-matousek commented
@lzaoral hi Lukas, this is a follow up to #157 based on your input

2024-05-06 10:59 UTC, lzaoral requested changes
Thnak you, @petr-matousek   The clippy plugin now works on RHEL 8 as well!

Remarks:
* nit:  The commit message for c34fe3a looks incomplete. 🤔
* I have found out that if the conversion script fails, `csmock` will still exit with `0` which is quite unexpected.  Could you please fix that as well?  Thank you!

2024-05-06 10:59 UTC, lzaoral commented on scripts/convert-clippy.py
> +                continue
note-to-self:  We should replace this with a `for` loop in the future when additional patterns will be needed to reduce nesting and code repetition.

2024-05-19 13:50 UTC, petr-matousek commented on scripts/convert-clippy.py
> +                continue
I tried to resolve your comments. please see the new set of commits.

2024-05-19 20:40 UTC, petr-matousek commented on make-srpm.sh
> +# failing as el7 rpmbuild defaults to Python 2.7 for Python scripts in unversioned directories
I tried to resolve your comments. please see the new set of commits.

2024-05-20 08:50 UTC, lzaoral commented on scripts/convert-clippy.py
> +                continue
Thank you very much, resolving this particular comment was not necessary!

2024-05-20 08:50 UTC, lzaoral commented on scripts/convert-clippy.py
> +            exit(1)
@petr-matousek See ^.

2024-05-20 08:55 UTC, lzaoral commented on scripts/convert-clippy.py
> +            exit(1)
The main issue with the exit code being ignored is still present and is cause by this piece of code:
https://github.com/csutils/csmock/blob/6b088e36d38a32b99b264b056c06e53e2fbe15f5/py/plugins/clippy.py#L41-L42

You have to enable the `pipefail` BASH shell option:
```shell
$ bash -c 'false | :'; echo $?
0
$ bash -c 'set -o pipefail; false | :'; echo $?
1
```

2024-05-21 08:03 UTC, petr-matousek commented on scripts/convert-clippy.py
> +            exit(1)
my shell programming abilities are obviously lacking behind. thanks for the hint -)

2024-05-23 13:03 UTC, kdudka commented
/packit rebuild-failed

2024-05-27 15:32 UTC, lzaoral commented on scripts/convert-clippy.py
> +            exit(1)
Thank you for the fixup!

2024-05-27 15:33 UTC, lzaoral approved these changes
LGTM!  Thank you @petr-matousek!

2024-05-27 17:12 UTC, kdudka commented
Merging, thank you both!

2024-05-27 17:12 UTC, merged