add plug-ins for CBMC, Divine, and Symbiotic
csutils/csmock pull request #35
Opened 2021-09-09 12:52 UTC by kdudka

2021-09-15 19:39 UTC, vmihalko commented on py/plugins/cbmc.py
> +
Since new upstream release of [cbmc-utils](https://github.com/aufover/cbmc-utils/releases/tag/v1.2) is already in fedora rawhide ([commit](https://src.fedoraproject.org/rpms/cbmc/c/96f17f8abfa823440b9c791fd8a27225291ff40)) this "hacking" line is not needed anymore.

2021-09-16 07:00 UTC, kdudka commented on py/plugins/cbmc.py
> +
Nice!  Removed via ba867f62c162aead32c01c06e508309241bb9020.

2021-09-16 07:26 UTC, lzaoral reviewed
I'm just wondering if setting `CC` and `CXX` to the desired compiler is really the right way to force it for the package. What about overriding `__cc`, `__cxx` and `__cpp` rpmbuild macros? https://src.fedoraproject.org/rpms/redhat-rpm-config/blob/rawhide/f/macros#_65

2021-09-16 07:46 UTC, lzaoral requested changes
I've added some comments, mainly highlighting and assigning TODOs.

2021-09-16 07:46 UTC, lzaoral commented on py/plugins/cbmc.py
> +        props.install_pkgs += ["cbmc"]
@vmihalko, shouldn't we install `cbmc-utils` as well?

2021-09-16 07:46 UTC, lzaoral commented on py/plugins/symbiotic.py
> +        # props.post_process_hooks += [cleanup_hook]
@lzaoral should finish this.

2021-09-16 07:46 UTC, lzaoral commented on py/plugins/symbiotic.py
> +        # TODO: assert that gllvm is installed properly
@lzaoral should finish this.

2021-09-16 07:46 UTC, lzaoral commented on py/plugins/divine.py
> +        # props.post_process_hooks += [cleanup_hook]
@lzaoral should finish this.

2021-09-16 07:46 UTC, lzaoral commented on py/plugins/cbmc.py
> +        #props.env["CXX"] = "goto-gcc"
@vmihalko Why is the `CXX` commented out? Were there any issues?

2021-09-16 07:46 UTC, lzaoral commented on py/plugins/cbmc.py
> +
@vmihalko probably just adapt the corresponding bits after I finish them in divine/symbiotic plug-ins.

2021-09-16 08:29 UTC, vmihalko reviewed
Looks good to me.

2021-09-16 08:29 UTC, vmihalko commented on py/plugins/cbmc.py
> +
OK.

2021-09-16 08:29 UTC, vmihalko commented on py/plugins/cbmc.py
> +        #props.env["CXX"] = "goto-gcc"
TODO for me.

2021-09-16 08:29 UTC, vmihalko commented on py/plugins/cbmc.py
> +        props.install_pkgs += ["cbmc"]
@kdudka will do this.

2021-09-16 10:34 UTC, kdudka commented
> I'm just wondering if setting `CC` and `CXX` to the desired compiler is really the right way to force it for the package. What about overriding `__cc`, `__cxx` and `__cpp` rpmbuild macros? https://src.fedoraproject.org/rpms/redhat-rpm-config/blob/rawhide/f/macros#_65

I would prefer to insert wrappers to `$PATH` but this can be worked on after merging this pull request upstream.

2021-09-16 10:35 UTC, kdudka commented on py/plugins/symbiotic.py
> +        # props.post_process_hooks += [cleanup_hook]
I think this is leftover from the `valgrind` plug-in, which this code is based on.  The cleanup hook does not need to be in all csmock plug-ins.

2021-09-16 10:42 UTC, kdudka commented on py/plugins/cbmc.py
> +        props.install_pkgs += ["cbmc"]
@lzaoral Thank you for pointing it out!  Resolved via 8a4b03945f0eb9a90dad51428006c6dd2e560c02.

2021-09-16 11:33 UTC, lzaoral commented on py/plugins/symbiotic.py
> +        # props.post_process_hooks += [cleanup_hook]
Hmm, it might actually be useful to leave empty logs be at the moment. It's not that they would consume too much space or resources. What do you think @vmihalko?

2021-09-16 11:42 UTC, vmihalko commented on py/plugins/symbiotic.py
> +        # props.post_process_hooks += [cleanup_hook]
I agree.

2021-09-16 12:01 UTC, kdudka commented on py/plugins/symbiotic.py
> +        # props.post_process_hooks += [cleanup_hook]
Perfect, marking as resolved.  Further tweaks will be appreciated via separate pull requests.

2021-09-16 12:16 UTC, lzaoral commented
I've noticed one other issue. `--tool-add-flag` will not actually work at the moment as we want to pass this additional flag to the tool and not to `csexec`.

2021-09-16 16:09 UTC, lzaoral commented on py/plugins/symbiotic.py
> +        # TODO: assert that gllvm is installed properly
Done.

2021-09-16 16:09 UTC, lzaoral commented on py/plugins/divine.py
> +        # props.post_process_hooks += [cleanup_hook]
Resolved.

2021-09-16 16:10 UTC, lzaoral commented on py/plugins/cbmc.py
> +
Resolved.

2021-09-16 16:16 UTC, lzaoral commented
I've updated the plug-ins to work correctly on Fedora 34. I've tested `gzip` and `zlib` and they seemed to work with `divine` and `symbiotic`. Unfortunately, i didn't have enough time to test then with `cbmc`. @vmihalko could you please have a look? Also, @psimovec, could you test all of the plug-ins that they work for you as well? Thank you both!

Note, that only rawhide has the new `cbmc-utils` at the moment.

2021-09-20 15:39 UTC, kdudka commented
Thanks for the update!  I tried it and it worked.

Divine failed to compile 2 of 3 packages that I tried (`hostname` and `units`) but it succeeded with `zlib` after commenting out all downstream patches:
```sh
Error: DIVINE_WARNING:
zlib-1.2.11/deflate.c: scope_hint: In function 'slide_hash':
zlib-1.2.11/deflate.c:219: error: conditional jump depends on an undefined value
zlib-1.2.11/deflate.c:219: note: control error in userspace
/opt/divine/include/dios/sys/fault.hpp:119: note: void __dios::FaultBase::handler<__dios::Context>(_VM_Fault, _VM_Frame*, void (*)())
zlib-1.2.11/deflate.c:219: note: slide_hash
zlib-1.2.11/deflate.c:1516: note: fill_window
zlib-1.2.11/deflate.c:1941: note: deflate_slow
zlib-1.2.11/deflate.c:1003: note: deflate
zlib-1.2.11/test/example.c:319: note: test_large_deflate
zlib-1.2.11/test/example.c:588: note: main
/opt/divine/include/dios/libc/sys/start.cpp:94: note: __dios_start
#  217|       do {
#  218|           m = *--p;
#  219|->         *p = (Pos)(m >= wsize ? m - wsize : NIL);
#  220|           /* If n is not on any hash chain, prev[n] is garbage but
#  221|            * its value will never be used.
```

Symbiotic had a few matches in `findutils-4.8.0-2.fc36` with `8s` timeout (the scan took 3 hours):
```sh
Error: SYMBIOTIC_WARNING:
findutils-4.8.0/build/gl/lib/../../../gl/lib/fflush.c:43: error: memory error: out of bound pointer
findutils-4.8.0/build/gl/lib/../../../gl/lib/fflush.c:43: note: call stack: clear_ungetc_buffer_preserving_position (=140357004731456)
findutils-4.8.0/build/gl/lib/../../../gl/lib/fflush.c:156: note: call stack: rpl_fflush (=140357004731456)
findutils-4.8.0/build/gnulib-tests/../../gnulib-tests/test-accept.c:42: note: call stack: main ()
#   41|   clear_ungetc_buffer_preserving_position (FILE *fp)
#   42|   {
#   43|->   if (fp->_flags & _IO_IN_BACKUP)
#   44|       /* _IO_free_backup_area is a bit complicated.  Simply call fseek.  */
#   45|       fseeko (fp, 0, SEEK_CUR);

Error: SYMBIOTIC_WARNING:
findutils-4.8.0/build/gl/lib/../../../gl/lib/freadahead.c:38: error: memory error: out of bound pointer
findutils-4.8.0/build/gl/lib/../../../gl/lib/freadahead.c:38: note: call stack: freadahead (=140281422305280)
findutils-4.8.0/build/gl/lib/../../../gl/lib/closein.c:87: note: call stack: close_stdin ()
/opt/symbiotic/lib/libc/atexit.c:13: note: call stack: RunAtExit ()
findutils-4.8.0/build/gnulib-tests/../../gnulib-tests/test-closein.c:48: note: call stack: main (=2, =0)
#   36|   #if defined _IO_EOF_SEEN || defined _IO_ftrylockfile || __GNU_LIBRARY__ == 1
#   37|     /* GNU libc, BeOS, Haiku, Linux libc5 */
#   38|->   if (fp->_IO_write_ptr > fp->_IO_write_base)
#   39|       return 0;
#   40|     return (fp->_IO_read_end - fp->_IO_read_ptr)

Error: SYMBIOTIC_WARNING:
findutils-4.8.0/build/gl/lib/../../../gl/lib/fseeko.c:52: error: memory error: out of bound pointer
findutils-4.8.0/build/gl/lib/../../../gl/lib/fseeko.c:52: note: call stack: rpl_fseeko (=140693433690112, =0, =1)
findutils-4.8.0/build/gl/lib/../../../gl/lib/fseek.c:29: note: call stack: rpl_fseek (=140693433690112, =0, =1)
findutils-4.8.0/build/gnulib-tests/../../gnulib-tests/test-fseek.c:41: note: call stack: main (=2, =0)
#   50|   #if defined _IO_EOF_SEEN || defined _IO_ftrylockfile || __GNU_LIBRARY__ == 1
#   51|     /* GNU libc, BeOS, Haiku, Linux libc5 */
#   52|->   if (fp->_IO_read_end == fp->_IO_read_ptr
#   53|         && fp->_IO_write_ptr == fp->_IO_write_base
#   54|         && fp->_IO_save_base == NULL)

Error: SYMBIOTIC_WARNING:
findutils-4.8.0/build/gl/lib/../../../gl/lib/xstrtol.c:127: error: memory error: out of bound pointer
findutils-4.8.0/build/gl/lib/../../../gl/lib/xstrtol.c:127: note: call stack: xstrtol (=0, =0, =0, =0, =0)
findutils-4.8.0/build/gnulib-tests/../../gnulib-tests/test-xstrtol.c:51: note: call stack: main (=2, =0)
#  125|       }
#  126|   
#  127|->   if (**p != '\0')
#  128|       {
#  129|         int base = 1024;

Error: SYMBIOTIC_WARNING:
findutils-4.8.0/build/gl/lib/../../../gl/lib/yesno.c:47: error: memory error: out of bound pointer
findutils-4.8.0/build/gl/lib/../../../gl/lib/yesno.c:47: note: call stack: yesno ()
findutils-4.8.0/build/gnulib-tests/../../gnulib-tests/test-yesno.c:60: note: call stack: main (=2, =0)
#   45|         /* Remove EOL if present as that's not part of the matched response,
#   46|            and not matched by $ for example.  */
#   47|->       if (response[response_len - 1] == '\n')
#   48|           response[response_len - 1] = '\0';
#   49|         yes = (0 < rpmatch (response));

Error: SYMBIOTIC_WARNING:
findutils-4.8.0/build/gnulib-tests/../../gnulib-tests/test-accept.c:42: error: reached "unreachable" instruction
findutils-4.8.0/build/gnulib-tests/../../gnulib-tests/test-accept.c:42: note: call stack: main ()
#   40|   
#   41|       errno = 0;
#   42|->     ASSERT (accept (-1, (struct sockaddr *) &addr, &addrlen) == -1);
#   43|       ASSERT (errno == EBADF);
#   44|     }

Error: SYMBIOTIC_WARNING:
findutils-4.8.0/build/gnulib-tests/../../gnulib-tests/test-accept.c:43: error: reached "unreachable" instruction
findutils-4.8.0/build/gnulib-tests/../../gnulib-tests/test-accept.c:43: note: call stack: main ()
#   41|       errno = 0;
#   42|       ASSERT (accept (-1, (struct sockaddr *) &addr, &addrlen) == -1);
#   43|->     ASSERT (errno == EBADF);
#   44|     }
#   45|     {

Error: SYMBIOTIC_WARNING:
findutils-4.8.0/build/gnulib-tests/../../gnulib-tests/test-bind.c:46: error: reached "unreachable" instruction
findutils-4.8.0/build/gnulib-tests/../../gnulib-tests/test-bind.c:46: note: call stack: main ()
#   44|       {
#   45|         errno = 0;
#   46|->       ASSERT (bind (-1, (const struct sockaddr *) &addr, sizeof (addr)) == -1);
#   47|         ASSERT (errno == EBADF);
#   48|       }

Error: SYMBIOTIC_WARNING:
findutils-4.8.0/build/gnulib-tests/../../gnulib-tests/test-bind.c:47: error: reached "unreachable" instruction
findutils-4.8.0/build/gnulib-tests/../../gnulib-tests/test-bind.c:47: note: call stack: main ()
#   45|         errno = 0;
#   46|         ASSERT (bind (-1, (const struct sockaddr *) &addr, sizeof (addr)) == -1);
#   47|->       ASSERT (errno == EBADF);
#   48|       }
#   49|       {
[...]
```

CBMC found something in `units-2.21-2.fc36`:
```sh
Error: CBMC_WARNING:
units-2.21/units.c:1570: error: pointer_arithmetic : pointer arithmetic: dead object in filename + (signed long int)return_value_strlen

Error: CBMC_WARNING:
units-2.21/units.c:1570: error: pointer_arithmetic : pointer arithmetic: deallocated dynamic object in filename + (signed long int)return_value_strlen

Error: CBMC_WARNING:
units-2.21/units.c:1570: error: pointer_arithmetic : pointer arithmetic: invalid integer address in filename + (signed long int)return_value_strlen

Error: CBMC_WARNING:
units-2.21/units.c:1570: error: pointer_arithmetic : pointer arithmetic: pointer NULL in filename + (signed long int)return_value_strlen

Error: CBMC_WARNING:
units-2.21/units.c:1570: error: pointer_arithmetic : pointer arithmetic: pointer invalid in filename + (signed long int)return_value_strlen

Error: CBMC_WARNING:
units-2.21/units.c:1570: error: pointer_arithmetic : pointer arithmetic: pointer outside object bounds in filename + (signed long int)return_value_strlen
```

I believe this is good enough to be merged!

2021-09-21 08:11 UTC, lzaoral commented
Cool, let's merge it then. Just out of curiosity what was the reason that `units` failed with `divine`? (I know that `hostname` fails due to some missing header in DiOS.)

2021-09-21 09:04 UTC, kdudka commented
`units` failed to compile with `divine` with this error message:
```
dioscc -O0 -O0  -o units units.o parse.tab.o getopt.o getopt1.o   -lm 
Symbol undefined (function): execve
make: *** [Makefile:104: units] Error 1
```

2021-09-21 09:06 UTC, closed without merging