WIP: no-cache parallel run
csutils/csmock pull request #48
Opened 2021-11-10 08:56 UTC by psimovec

WIP - still does not work properly in all cases (I dh delete my personal comments so far)

added arguments:
--no-cache disables yum_cache and root_cache, allows parallel run
--rootdir sets rootdir for mock, however I however I had 0 success using this argument
--config-opts (--config-opts=root=root_directory) so far, passes this instance to mock just once (mock allows multiple uses)

note: --rootdir=xyz behaves differently than --config-opts=root=xyz

2021-11-10 13:56 UTC, kdudka requested changes
Let's do just one thing at a time and do it properly.  If I remember correctly, we needed just the `--resultdir` option.  So I would not add the other two options until we have a use case for them.  We already have too many options in csmock.

Please also remove all unrelated changes from commit(s) that add new features or change the behavior, like the reorder/reindent of imports.

And please avoid any non-English comments in public pull requests.

2021-11-10 14:00 UTC, kdudka commented
Sorry for the typo.  I meant `--rootdir`, of course.

2021-11-10 14:46 UTC, psimovec commented
> Let's do just one thing at a time and do it properly. If I remember correctly, we needed just the `--rootdir` option. So I would not add the other two options until we have a use case for them. We already have too many options in csmock.


That's the problem, I'd love to just keep just --rootdir, but as I have commented I had 0 success with --rootdir. --rootdir just does not work the same way as --config-opts=root=directory as we have expected.

2021-11-10 15:21 UTC, kdudka commented
I meant csmock's `--rootdir` option.  It can be implemented by using multiple mock's option underneath, of course.  Let's just not complicate csmock's interface by these implementation details.

As for the locking issue, I believe it could be easily fixed.  `MockWrapper` just needs to use something else as the lock name in case `--rootdir` is used.

2021-11-11 08:12 UTC, psimovec commented
> I meant csmock's `--rootdir` option. It can be implemented by using multiple mock's option underneath, of course. Let's just not complicate csmock's interface by these implementation details.
> 
> As for the locking issue, I believe it could be easily fixed. `MockWrapper` just needs to use something else as the lock name in case `--rootdir` is used.

Changing lock name in MockWrapper has no effect. Running a process in parallel causes a quick error:
```
2021-11-11 08:55:53	"/usr/bin/mock" "-r" "default" "--plugin-option=tmpfs:keep_mounted=True" "--config-opts=print_main_output=True" "--rootdir=/var/lib/mock/pes71" "--disable-plugin=root_cache" "--disable-plugin=yum_cache" "--init"
INFO: mock.py version 2.12 starting (python version = 3.9.7, NVR = mock-2.12-1.fc34)...
Start(bootstrap): init plugins
INFO: selinux enabled
Finish(bootstrap): init plugins
Start: init plugins
INFO: selinux enabled
Finish: init plugins
INFO: Signal handler active
Start: run
Start: clean chroot
ERROR: Build root is locked by another process.

!!! 2021-11-11 08:55:54	fatal error: failed to init mock profile (default)
```

Let me point out again, `--config-opts=root=directory` works for me. `--rootdir` is not a simple shortcut for `--config-opts=root=` as it for some reason behaves differently, especially when run in parallel. I think we should use only `--config-opts=root=` argument on mock (but we can call it differently in csmock), and to remove `--rootdir` argument.

2021-11-11 13:47 UTC, kdudka commented
OK, got it.  This is a problem with the lock of **mock** itself.  If it works fine with `mock --config-opts=root=directory ...`, let's use that and introduce a new option in csmock for it.  I would just use a different name for the csmock option when it expects a different value than mock's `--rootdir`.  What about `--root-override`?

2021-11-16 08:21 UTC, kdudka requested changes

2021-11-16 08:21 UTC, kdudka commented on py/csmock
> +                  "to run this csmock instance in parallel")
This should be printed to log via `self.results.print_with_ts()` rather than to standard output.

2021-11-16 08:21 UTC, kdudka commented on py/csmock
> +    parser.add_argument("--no-cache", action="store_true",
I do not think we need `--no-cache` in csmock's public interface when its only use case is in combination with `--root-override`.  This should be an implementation detail internal to the `MockWrapper` class.

2021-11-16 08:24 UTC, kdudka commented on py/csmock
> +                  "to run this csmock instance in parallel")
Also the extra invocation of `cmd` should not be needed to print this message.

2021-11-19 09:41 UTC, kdudka commented on py/csmock
> +            f"-{props.mock_root_override}" if props.mock_root_override else ""
The lock name is not optimal.  If we run two instances of csmock like this:
```
csmock -r fedora-34-x86_64 --root-override=xxx ...
csmock -r fedora-35-x86_64 --root-override=xxx ...
```
... they clash with each other.  With `--root-override` specified, we should rather use `self.mock_root_override` on its own as a substitution for `self.mock_profile` in the lock name.  This will also protect the case where someone uses `--root-override=fedora-35-x86_64` as long as system-provided mock profiles use their name for the `root` config option.  This seems to be the case for all profiles in `mock-core-configs` and `csmock-core-configs`.

Please move the `self.mock_root_override = props.mock_root_override` up, so that we do not mix accesses via `self.` and `props.` in the substitutions.

2021-11-19 09:47 UTC, kdudka commented on py/csmock
> +                self.results.print_with_ts("\ntip: you can use --root-override=<directory> "
The leading `\n` makes the output look inconsistent:
```
>>> 2021-11-19 10:20:55
tip: you can use --root-override=<directory> to run this csmock instance in parallel
>>> 2021-11-19 10:20:55 waiting till .lock (PID 3652) disappears...
>>> 2021-11-19 10:21:55 waiting till .lock (PID 3652) disappears...
```
I propose to drop it.

2021-11-23 14:47 UTC, kdudka approved these changes
Looks perfect, merging now.  Thanks!

2021-11-23 14:47 UTC, closed without merging