divine: pass `-o ignore:notimplemented` to Divine
csutils/csmock pull request #59
Opened 2021-12-08 16:07 UTC by lzaoral

Divine will not report calls to undefined functions as an fatal error.

2021-12-08 16:42 UTC, kdudka requested changes

2021-12-08 16:42 UTC, kdudka commented on py/plugins/divine.py
> +                      f"-o ignore:exit -max-time {args.divine_timeout}"]
It seems that one dash from `--max-time` was removed by mistake, which prevented divine from starting:
```
ERROR: could not parse command
synopsis: /usr/bin/divine check [options] {file} {vector}*
command:  /usr/bin/divine check --lart stubs -o ignore:notimplemented -o ignore:exit -max-time 150 --stdin /tmp/divine-stdinLKBC --capture ././minigzip --threads 2 --report-filename /build
matched:  --lart stubs             as --lart {vector}
matched:  -o ignore:notimplemented as -o{vector}
matched:  -o ignore:exit           as -o{vector}
file -max-time does not exist
failed to match '-max-time'
```

2021-12-08 17:14 UTC, lzaoral commented on py/plugins/divine.py
> +                      f"-o ignore:exit -max-time {args.divine_timeout}"]
Good catch! Thanks!

2021-12-09 08:28 UTC, kdudka approved these changes
Thanks for the update!  Merging...

2021-12-09 08:28 UTC, merged