cbmc: do not convert the outputs on host
csutils/csmock pull request #61
Opened 2022-02-10 08:44 UTC by vmihalko

This change is similar to https://github.com/csutils/csmock/pull/47.
I move the conversion into cbmc-utils/csexec-cbmc.sh: https://github.com/aufover/cbmc-utils/commit/f7b4f2ec40d8c2ed2179de83a936710911a21899.

2022-02-10 09:54 UTC, kdudka requested changes
Thank you for working on it!  Please also remove the dependency on `cbmc-utils` in spec file (embedded in `make-srpm.sh`).

2022-02-10 09:54 UTC, kdudka commented on py/plugins/cbmc.py
> +            cmd = f"csgrep --mode=json --remove-duplicates {src_dir}/pid-*.conv > {dst}"
I would prefer to write it as:
```py
 cmd = f"cd '{src_dir}' && touch empty.conv && csgrep --mode=json --remove-duplicates *.conv > '{dst}'"
```

Otherwise we would reintroduce the issue that 5c31ee11547cb3485b4c395db4fb270ea4f7292c tried to avoid (the `touch empty.conv` part was introduced in d47d9b3b2ded03d25f2e002d049c89a0eb3b9978).

2022-03-18 12:26 UTC, vmihalko commented
I'm sorry - this PR completely slipped my mind.

2022-03-18 12:27 UTC, vmihalko commented on py/plugins/cbmc.py
> +            cmd = f"csgrep --mode=json --remove-duplicates {src_dir}/pid-*.conv > {dst}"
Resolved in https://github.com/csutils/csmock/pull/61/commits/ef501ee23ebb0d9e241a8f97000405f34e84a8b5.

2022-03-18 12:33 UTC, kdudka commented
No worries.  Better later than never :-)

Please also remove the dependency on `cbmc-utils` in spec file (embedded in `make-srpm.sh`).

2022-03-18 15:28 UTC, kdudka commented
Merging, thanks!

2022-03-18 15:28 UTC, closed without merging